apiVersion: v1
kind: Service
metadata:
  name: {{ include "thunai-sentinel.fullname" . }}
  labels:
    {{- include "thunai-sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dashboard
      protocol: TCP
      name: http
  selector:
    {{- include "thunai-sentinel.selectorLabels" . | nindent 4 }}
